fn main() {
    let crate_dir = std::env::var("CARGO_MANIFEST_DIR").unwrap();

    let config = cbindgen::Config {
        language: cbindgen::Language::C,
        include_guard: Some("PITA_H".into()),
        autogen_warning: Some("/* Auto-generated by cbindgen. Do not edit. */".into()),
        cpp_compat: true,
        parse: cbindgen::ParseConfig {
            parse_deps: false,
            clean: false,
            ..Default::default()
        },
        ..Default::default()
    };

    cbindgen::Builder::new()
        .with_crate(&crate_dir)
        .with_config(config)
        .generate()
        .expect("Unable to generate bindings")
        .write_to_file("pita.h");
}
